spring:
  flyway:
    url: jdbc:postgresql://${R2DBC_HOST}:${R2DBC_PORT}/${R2DBC_DATABASE}
    user: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
    default-schema: ${R2DBC_SCHEMA}

aws:
  region: "${AWS_REGION}"
  rds:
    postgres:
      secretName: "${AWS_RDS_POSTGRES_SECRET_NAME}"
  jwt:
    secretName: "${AWS_JWT_SECRET_NAME}"

logging:
  level:
    root: INFO